
version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/src/kwd.CoreDomain.Samples"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/src/kwd.CoreDomain.Tests"
    schedule:
      interval: "weekly"